services:
  - type: web
    name: my-pentashop-world
    env: node
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true 