name: wash-the-world-platform
services:
  - name: frontend
    source_dir: /frontend
    github:
      repo: your-username/my.pentashop.world
      branch: main
    build_command: npm run build
    run_command: npm run preview
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${backend_url}

  - name: backend
    source_dir: /backend
    github:
      repo: your-username/my.pentashop.world
      branch: main
    build_command: npm install
    run_command: node src/index-simple.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: ${frontend_url}

databases:
  - name: wash-the-world-db
    engine: PG
    version: "12"
    size: db-s-1vcpu-1gb 